"""web-researcher-mcp — typed Python SDK for web research, citation verification, and bibliography auditing.

CLI usage:
    uvx web-researcher-mcp          # MCP server over STDIO
    PORT=8080 uvx web-researcher-mcp # MCP server over HTTP

Python SDK usage:
    from web_researcher_mcp import WebResearcherClient

    async with WebResearcherClient() as client:
        results = await client.web_search("CRISPR off-target effects 2024")

    # Sync (no async/await needed):
    with WebResearcherClient.sync() as client:
        results = client.web_search("climate change 2024")
"""
# AUTO-GENERATED — do not edit by hand.
# Run: make gen-python-client
from __future__ import annotations

from web_researcher_mcp._shim import __version__, get_binary_path, main  # noqa: F401
from web_researcher_mcp.client import SyncWebResearcherClient, WebResearcherClient  # noqa: F401
from web_researcher_mcp.models import (  # noqa: F401
    AcademicPaper,
    AcademicSearchPaper,
    AcademicSearchResponse,
    Analytics,
    AnswerCitation,
    AnswerResponse,
    ArchiveResult,
    ArchiveSourceResponse,
    AuditBibliographyEntry,
    AuditBibliographyResponse,
    AuditBibliographyResult,
    AuditBibliographySummary,
    AuditSummary,
    AwesomeListSearchList,
    AwesomeListSearchResponse,
    BibEntryAudit,
    Body,
    BrandResearchPalette,
    BrandResearchResponse,
    BrandResearchScale,
    BrandResearchSource,
    Citation,
    CitationGraphCitedby,
    CitationGraphResponse,
    ClinicalSearchResponse,
    ClinicalSearchTrial,
    Colors,
    ConflictOfInterest,
    Coverage,
    Dark,
    DosAndDonts,
    EconSearchResponse,
    EconSearchResult,
    Engagement,
    FilingSearchFiling,
    FilingSearchResponse,
    FormatBibliographyResponse,
    Formatted,
    ForumSignals,
    GetMyAnalyticsResponse,
    GetResearchSessionErrorpattern,
    GetResearchSessionGap,
    GetResearchSessionLaststep,
    GetResearchSessionResponse,
    GetResearchSessionSource,
    GetResearchSessionStepindex,
    Identity,
    ImageResult,
    ImageSearchImage,
    ImageSearchResponse,
    LegalSearchCas,
    LegalSearchResponse,
    LocalSearchPlace,
    LocalSearchResponse,
    Location,
    Logos,
    MCPError,
    MemoryRecallMemory,
    MemoryRecallResponse,
    MemorySaveResponse,
    Metadata,
    NewsArticle,
    NewsSearchArticle,
    NewsSearchResponse,
    PatentSearchPatent,
    PatentSearchResponse,
    ResearchExportResponse,
    RetractionStatus,
    ScrapePageMetadata,
    ScrapePageResponse,
    ScrapeResult,
    SearchAndScrapeComponent,
    SearchAndScrapeRecommendation,
    SearchAndScrapeResponse,
    SearchAndScrapeResult,
    SearchAndScrapeScrapefailure,
    SearchAndScrapeSource,
    SearchResponse,
    SearchResult,
    SequentialSearchCoverage,
    SequentialSearchRefinementresult,
    SequentialSearchResponse,
    SequentialSearchResult,
    SizeMetadata,
    Social,
    StructuredData,
    StructuredSearchResponse,
    StructuredSearchResult,
    Summary,
    ToneOfVoice,
    Typography,
    VerifyCitationResponse,
    VerifyRecommendationConflictOfInterest,
    VerifyRecommendationCorroborationsearch,
    VerifyRecommendationRecommendation,
    VerifyRecommendationResponse,
    VerifyResult,
    WebSearchResponse,
    WebSearchResult,
    WorkspaceContributeResponse,
    WorkspaceReadContribution,
    WorkspaceReadResponse,
)

__all__ = [
    "__version__",
    "get_binary_path",
    "main",
    "WebResearcherClient",
    "SyncWebResearcherClient",
    "AcademicPaper",
    "AcademicSearchPaper",
    "AcademicSearchResponse",
    "Analytics",
    "AnswerCitation",
    "AnswerResponse",
    "ArchiveResult",
    "ArchiveSourceResponse",
    "AuditBibliographyEntry",
    "AuditBibliographyResponse",
    "AuditBibliographyResult",
    "AuditBibliographySummary",
    "AuditSummary",
    "AwesomeListSearchList",
    "AwesomeListSearchResponse",
    "BibEntryAudit",
    "Body",
    "BrandResearchPalette",
    "BrandResearchResponse",
    "BrandResearchScale",
    "BrandResearchSource",
    "Citation",
    "CitationGraphCitedby",
    "CitationGraphResponse",
    "ClinicalSearchResponse",
    "ClinicalSearchTrial",
    "Colors",
    "ConflictOfInterest",
    "Coverage",
    "Dark",
    "DosAndDonts",
    "EconSearchResponse",
    "EconSearchResult",
    "Engagement",
    "FilingSearchFiling",
    "FilingSearchResponse",
    "FormatBibliographyResponse",
    "Formatted",
    "ForumSignals",
    "GetMyAnalyticsResponse",
    "GetResearchSessionErrorpattern",
    "GetResearchSessionGap",
    "GetResearchSessionLaststep",
    "GetResearchSessionResponse",
    "GetResearchSessionSource",
    "GetResearchSessionStepindex",
    "Identity",
    "ImageResult",
    "ImageSearchImage",
    "ImageSearchResponse",
    "LegalSearchCas",
    "LegalSearchResponse",
    "LocalSearchPlace",
    "LocalSearchResponse",
    "Location",
    "Logos",
    "MCPError",
    "MemoryRecallMemory",
    "MemoryRecallResponse",
    "MemorySaveResponse",
    "Metadata",
    "NewsArticle",
    "NewsSearchArticle",
    "NewsSearchResponse",
    "PatentSearchPatent",
    "PatentSearchResponse",
    "ResearchExportResponse",
    "RetractionStatus",
    "ScrapePageMetadata",
    "ScrapePageResponse",
    "ScrapeResult",
    "SearchAndScrapeComponent",
    "SearchAndScrapeRecommendation",
    "SearchAndScrapeResponse",
    "SearchAndScrapeResult",
    "SearchAndScrapeScrapefailure",
    "SearchAndScrapeSource",
    "SearchResponse",
    "SearchResult",
    "SequentialSearchCoverage",
    "SequentialSearchRefinementresult",
    "SequentialSearchResponse",
    "SequentialSearchResult",
    "SizeMetadata",
    "Social",
    "StructuredData",
    "StructuredSearchResponse",
    "StructuredSearchResult",
    "Summary",
    "ToneOfVoice",
    "Typography",
    "VerifyCitationResponse",
    "VerifyRecommendationConflictOfInterest",
    "VerifyRecommendationCorroborationsearch",
    "VerifyRecommendationRecommendation",
    "VerifyRecommendationResponse",
    "VerifyResult",
    "WebSearchResponse",
    "WebSearchResult",
    "WorkspaceContributeResponse",
    "WorkspaceReadContribution",
    "WorkspaceReadResponse",
]
